version: '2'
services:
  git_listener:
    env_file: .env
    environment:
      DEFAULT_LISTENER_PORT: ${DEFAULT_LISTENER_PORT}
      CONF_SERVER_TOKEN: ${CONF_SERVER_TOKEN}
      VAULT_TOKEN: ${VAULT_TOKEN}
      ENV_ID: ${ENV_ID}
      QUBE_URL: http://qube_platform/api/v1/webhooks/
    image: ${GIT_LISTENER_IMAGE}:${GIT_LISTENER_VERSION}
    ports:
      - "${DEFAULT_LISTENER_PORT}:80"

#  ngrok:
#    env_file: .env
#    environment:
#      NGROK_AUTH: ${NGROK_AUTH}
#      NGROK_HOSTNAME: ${NGROK_HOSTNAME}
#      NGROK_PROTOCOL: ${NGROK_PROTOCOL}
#      NGROK_PORT: ${NGROK_PORT}
#    image: wernight/ngrok
#    command: [ngrok , http,"--authtoken", "${NGROK_AUTH}" , "--hostname",
#    "${NGROK_HOSTNAME}",
#    "http:${DEFAULT_LISTENER_PORT}"]
#    ports:
#      - "4040:4040"
#    links:
#      - git_listener:http
