---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qube-git-listener
  name: git-listener-service
  namespace: platform
spec:
  ports:
  - port: 80
  selector:
    app: qube-git-listener
  type: LoadBalancer
